import { APIError } from "../types/APIError";
import { tenancyErrorMessage } from "./TenancyConstants";

export const MAX_EMBARGO_DAYS = 90;

export const REDACTED = "[redacted]";

export const ANONYMOUS_LINK_LABEL_MAX = 256;

export const GENERIC_ERROR_MESSAGE = "Something went wrong. Please try again.";

export const EMBARGO_ERROR_MESSAGES: Record<string, string> = {
    embargo_too_long: "An embargo can last at most 90 days from today.",
    embargo_until_in_past: "Choose a date in the future.",
    embargo_dataset_published: "This dataset has already been published, so it cannot be embargoed.",
    embargo_already_active: "This dataset is already under embargo.",
    embargo_not_active: "This dataset is not under embargo.",
    embargo_until_not_later: "The new date must be later than the current end of the embargo.",
    embargo_active: "This cannot be done while the dataset is under embargo.",
    share_target_required: "Choose a person, or type an email or ORCID.",
    share_target_ambiguous: "Type only one email or ORCID.",
    invalid_email: "This email address is not valid.",
    invalid_orcid: "This ORCID is not valid. Check the last digit.",
    already_has_access: "This person already has access.",
    cannot_share_with_owner: "The owner already has access.",
    invalid_level: "Choose a valid access level.",
    unknown_user: "This person has no active DataMap account.",
    embargo_manual_doi: "This dataset has a manual DOI, so it can no longer be put under embargo.",
    embargo_manual_doi_ends_embargo: "Registering a manual DOI ends the embargo. Confirm it, or use a DOI generated by DataMap.",
};

export function messageForApiError(error: unknown, fallback: string = GENERIC_ERROR_MESSAGE): string {
    const apiError = error as APIError;
    const code = apiError?.errors?.[0]?.code;

    if (code && EMBARGO_ERROR_MESSAGES[code]) {
        return EMBARGO_ERROR_MESSAGES[code];
    }
    const detail = typeof apiError?.detail === "string" ? apiError.detail : undefined;
    if (detail === "public_members_cannot_edit" || detail === "tenancy_cannot_change") {
        return tenancyErrorMessage(detail);
    }
    if (apiError?.httpCode === 403) {
        return "You are not allowed to do this on this dataset.";
    }
    if (apiError?.httpCode === 404) {
        return "This dataset no longer exists, or you no longer have access to it.";
    }
    return fallback;
}
